idf_component_register(
    SRCS
        "main.c"
        "debug.c"
        "power.c"
        "adc_sense.c"
        "wifi_sta.c"
        "camera.c"
        "telemetry.c"
        "cloud_check.c"
        "presuppress.c"
        "batch_store.c"
        "ota.c"
        "http_client.c"
        "camera_server.c"
        "diag.c"
    INCLUDE_DIRS
        "."
    PRIV_REQUIRES
        nvs_flash
        esp_wifi
        esp-idf-lib__ds3231
        esp-idf-lib__i2cdev
        esp_event
        esp_netif
        esp_http_client
        esp_http_server
        lwip
        esp_adc
        esp_timer
        esp_driver_gpio
        espressif__cjson
        spi_flash
        spiffs
        esp_psram
        esp_hw_support
        esp_pm
        log
        app_update
        esp_app_format
)
