// Generated by src/cloud-check/presuppress_model.py — do not edit by hand.
// Suppression score per (solar elevation x quiet gap x burst position) cell.
// Fitted on 1838 PIR events / 68 labelled birds over 45 days.
// Cross-validated zero-loss suppression: 27.1% (reference model 22.0%).
// Shipped threshold 40 suppresses 34.8% of PIR events.
// Out-of-fold bird loss at that point: 3/68 — those are NOT lost,
// they arrive as `batched` rows with a thumbnail for review.
#pragma once
#include <stdint.h>

#define BW_PS_N_ELEV   8
#define BW_PS_N_GAP    6
#define BW_PS_N_BURST  4
#define BW_PS_BURST_MAX 3

// Band edges — must match presuppress_model.py exactly.
static const float BW_PS_ELEV_EDGES[7] = {0.0f, 5.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f};
static const float BW_PS_GAP_EDGES[5]  = {15.0f, 60.0f, 300.0f, 1800.0f, 7200.0f};

// Default threshold for ~35% suppression; overridden by NVS "ps_thr".
#define BW_PS_DEFAULT_THRESHOLD 40

// Score 0-255; suppress when score < threshold.
static const uint8_t BW_PS_TABLE[192] = {
     13,   7,  17,  17,  89,  83, 103, 103, 106,  96, 109, 109,
     26,  23,  30,  30,  53,  50,  56,  56,  86,  76,  93,  93,
     66,  66,  73,  73, 242, 242, 252, 252, 212, 212, 229, 229,
    129, 129, 136, 136, 172, 172, 176, 176, 219, 219, 232, 232,
     99,  99, 113, 113, 238, 238, 245, 245, 209, 209, 222, 222,
    152, 152, 156, 156, 225, 225, 235, 235, 248, 248, 255, 255,
     60,  60,  63,  63, 195, 195, 199, 199, 179, 179, 185, 185,
    132, 132, 139, 139, 182, 182, 189, 189, 202, 202, 205, 205,
     43,  43,  43,  43, 159, 159, 159, 159, 169, 169, 169, 169,
    119, 119, 119, 119, 162, 162, 162, 162, 166, 166, 166, 166,
     33,  33,  33,  33, 126, 126, 126, 126, 142, 142, 142, 142,
    149, 149, 149, 149, 192, 192, 192, 192, 215, 215, 215, 215,
      3,   3,   3,   3,  36,  36,  36,  36,  40,  40,  40,  40,
     70,  70,  70,  70, 123, 123, 123, 123, 146, 146, 146, 146,
      0,   0,   0,   0,  10,  10,  10,  10,  20,  20,  20,  20,
     46,  46,  46,  46,  79,  79,  79,  79, 116, 116, 116, 116,
};
