#pragma once
// ─── Pre-suppression: is this PIR trigger already EXPLAINED? ─────────────────
//
// Detecting a bird on-device was measured to be impossible on this scene — a
// bird is ~100 anomalous pixels in 480k, smaller than the background noise.
// This asks the inverse, which is far better posed for a microcontroller:
// was the trigger already explained by the time of day and the recent trigger
// pattern?  Rapid cloud changes re-fire the PIR in bursts; a long quiet spell
// means something actually arrived.
//
// Measured (1838 PIR events, 68 labelled birds, 45 days, cross-validated by
// date): solar elevation + quiet gap + burst position suppress 34.8% of PIR
// events at 3/68 out-of-fold bird loss.  Adding image features made it WORSE
// at every operating point — they were fitting noise.  So this module reads
// NO image data at all and runs BEFORE the camera is powered on.
//
// Suppressed events are not discarded: main.c stores a thumbnail plus these
// fields via batch_store, and they reach the server as `batched` rows.  That
// is what makes an aggressive threshold safe — a wrong suppression is
// reviewable rather than invisible.
//
// The scoring table is generated by src/cloud-check/presuppress_model.py into
// presuppress_table.h.  Do not hand-edit it, and keep the band edges and the
// solar formula in step with that script.

#include "esp_err.h"
#include <stdbool.h>
#include <stdint.h>
#include <time.h>

typedef struct {
    bool    suppress;      // true → skip WiFi, store a batched record instead
    uint8_t score;         // 0-255 from the lookup table (low = likely explained)
    uint8_t threshold;     // effective threshold (NVS "ps_thr", else the default)
    float   solar_elev;    // degrees above horizon; negative at night
    int32_t quiet_gap_s;   // seconds since the previous PIR event (-1 if unknown)
    uint8_t burst_pos;     // consecutive triggers <60 s apart (0 = first)
    char    why[12];       // "SCORE" | "PROCEED" | "RTC" | "NO_TIME"
} bw_presup_t;

// Solar elevation in degrees for a UTC epoch.  Mirrors solar_elevation() in
// presuppress_model.py — change both together or the table stops meaning
// what it was fitted to mean.
float bw_presup_solar_elev(time_t now_utc);

// Decide, without touching the camera.  RTC frames are never suppressed: they
// are the proof-of-life and they guarantee the batch store gets flushed.
// now_utc == 0 (RTC unreadable) also never suppresses — no clock, no decision.
esp_err_t bw_presup_decide(time_t now_utc, bool is_pir, bw_presup_t *out);

// Persist the event time and burst counter.  Call on EVERY path (suppressed or
// not) so the quiet-gap and burst-position features stay correct; only PIR
// events advance the state, matching how the rule was fitted.
void bw_presup_commit(time_t now_utc, bool is_pir);

// Emit the decision as telemetry.  Safe to call on any path.
void bw_presup_telemetry(const bw_presup_t *d);
